name: Build frontend & push artifacts to S3
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      branch:
        required: true
        type: string
      s3-bucket:
        required: true
        type: string
      aws-role:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: ap-southeast-1
      output:
        required: false
        type: string
        default: build
      command:
        required: false
        type: string
        default: |
          unset CI
          npm ci
          npm run build
      build-latest-tag:
        required: false
        type: boolean
        default: true
      node-version:
        required: false
        type: string
        default: 20
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
      - run: (${{ inputs.command }})
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}
      - uses: nobitacnt-demo/devops-actions/actions/push-s3-artifact@master
        with:
          bucket: ${{ inputs.s3-bucket }}
          project: ${{ inputs.project }}
          branch: ${{ inputs.branch }}
          path: ${{ inputs.output }}
          build-latest-tag: ${{ inputs.build-latest-tag }}
