name: Node CI
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: 14
    secrets:
      docker-username:
        required: true
      docker-password:
        required: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Make image tags
        id: make-tags
        uses: nobitacnt-demo/devops-actions/actions/make-image-tags@master
        with:
          repository: ${{ inputs.repository }}
          branch: ${{ inputs.branch }}
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.make-tags.outputs.tags }}
